apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-voll
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4
